//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 01:31:53 PM EDT 
//
package com.studentgrade.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}student" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gradebook"
})
@XmlRootElement(name = "gradebook-list")
public class GradeBookList {

    protected List<GradeBook> gradebook;
    public List<GradeBook> getGradeBook() {
        if (gradebook == null) {
        	gradebook = new ArrayList<GradeBook>();
        }
        return this.gradebook;
    }

    public void setGradeBook(List<GradeBook> gradebookList) {
        this.gradebook = gradebookList;
    }

    public void addGradeBook(GradeBook gb) {
        if (gradebook == null) {
        	gradebook = new ArrayList<GradeBook>();
        }
        this.gradebook.add(gb);
    }
}
